### ISSUE TITLE
Provide an apk on github

### ISSUE THREAD

**Issue by adisib** [bleeding182/minimalist-flashlight#3]
I am migrating away from the Google Play Store for a multitude of reasons. All of the flashlights on Fdroid do not look to be what I am looking for like yours is. Could you please make an apk release here on github so that the app can be side-loaded?

**Comment by bleeding182** [comment]
Hey!

I might add it in the future, but for now you can just follow the CircleCI badge and add the `#artifacts` tag to the latest CI build to access the outputs.

e.g. https://circleci.com/gh/bleeding182/minimalist-flashlight/53#artifacts

On 23+ you want to use the marshmallow flavor
